services:
  - type: web
    name: cupcake-magic-garden-backend
    runtime: python3
    rootDir: lakeishas_cupcakery
    build:
      os: ubuntu22.04
      commands:
        - pip install -r requirements.txt
        - python manage.py collectstatic --noinput
        - python manage.py migrate
    envVars:
      - key: PYTHON_VERSION
        value: "3.9.0"
      - key: DJANGO_SETTINGS_MODULE
        value: "config.settings.prod"
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
    startCommand: "gunicorn config.wsgi:application --bind 0.0.0.0:$PORT"
    plan: free
    numInstances: 1
    healthCheckPath: "/api/"
    regions:
      - "iad1"
    autoDeploy: true

databases:
  - name: postgres
    databaseName: cupcake_magic_garden
    user: postgres
    plan: free